### ISSUE TITLE
[BUG] 3.1.x thinks I'm sending lots of keys

### ISSUE THREAD

**Issue by yyolk** [kraanzu/smassh#82]
### Describe the bug 🐛

I've tried reinstalling and deleting my settings

When running smassh @ 3.1.0 - it interprets each character I write as more than one

### To Reproduce 🐣

1. Delete `smassh` configuration json 
2. Install 3.1.0 via pipx, with `pipx install smassh`
3. Start `smassh`, it interprets each character as more than one

### Expected behavior 🤔

Only one character is pressed per key.

### Screenshots 🧐

typing '<kbd>h</kbd><kbd>o</kbd><kbd>m</kbd><kbd>e</kbd>', the first character is recognized, but thinks I also pressed many more I guess, proceeding to continue to type <kbd>o</kbd><kbd>m</kbd><kbd>e</kbd>- the cursor is placed on the last character of the 2nd word, 8 characters away or double in length from where it should be.
![image](https://github.com/kraanzu/smassh/assets/134478/b5c0d72d-9c0d-46e3-8000-02bfe07de51b)

### Your operating system name

Mac

### Your operating system version

Sonoma 14.3.1

### Additional context 📝

If I delete the configuration and downgrade to `smassh==3.0.*`, with:

-  `pipx uninstall smassh`
- `rm ~/Library/Application\ Support/smassh/smassh.json` (where `smassh` keeps its configuration instead of `$HOME`)
- `pipx install smassh==3.0.*`
- Run `smassh` - it works as it used to, and correctly

If I don't delete my configuration, other weird things happen like not interpreting any mistakes and not changing character colors.

**Comment by jaxvanyang** [comment]
![image](https://github.com/kraanzu/smassh/assets/25650612/e78be827-ea82-4385-9923-8b4e9706389d)

Same issue here, smassh thinks I type twice every time, look the pattern ("tt" is marked correct, others are correct then incorrect). Deleting config doesn't work. Backspace is also consider typing twice every time.

![image](https://github.com/kraanzu/smassh/assets/25650612/5e26ef92-8645-437e-bcf4-a5c22e74fbac)

But when I enter the next test, this issue is gone.

My system is Arch Linux in WSL, smassh is installed from AUR, it's the same file from GitHub release.

**Comment by kraanzu** [comment]
> Changing to any window solves this issue, i.e., settings, help, about.

Ah I see now, maybe the key event is propagating.
Thanks for opening a PR!
